@baseUri=https://localhost:7012/Teczter

###

GET {{baseUri}}/Test

###

GET {{baseUri}}/Test?testName=testest

###

GET {{baseUri}}/Test?testName=test&owningDepartment=Accounting

###

GET {{baseUri}}/Test/4

###

